### ISSUE TITLE
roshask fails to build on Windows

### ISSUE THREAD

**Issue by dfarmer** [acowley/roshask#45]
Hi Anthony,

When attempting to build on Windows 10 x64 (using `stack build`) I hit:

`    
    [35 of 38] Compiling Ros.Node.RunNode ( src\Ros\Node\RunNode.hs, .stack -
     work\dist\b7fec021\build\Ros\Node\RunNode.o
      )

    C:\Users\dan_f\src\roshask\src\Ros\Node\RunNode.hs:6:1: error:
        Failed to load interface for 'System.Posix.Signals'
        Perhaps you meant System.Posix.Internals (from base-4.9.0.0)
        Use -v to see a list of the files searched for.`

Given that I'm on Windows this is not a complete surprise, but the wiki mentions running on Windows so I'm just checking to see if this should have been expected to work or not? If I can help fix it I'd be happy to if I could get a nudge in the right direction.

**Comment by acowley** [comment]
It looks like it's limited to shutting things down, so there should be multiple ways of doing so. I'm not sure why this is done the way it is rather than something based on the Haskell-level `UserInterrupt` exception. I don't think that commenting all this stuff out would be a bad idea if you just want to get un-stuck to see if the rest of the build goes smoothly.

**Comment by dfarmer** [comment]
That did work. Still fighting a little bit with ROS itself (roscreate-pkg, etc). I don't really know how exception handling in Haskell works, but if it's easy to tell how to test it I can try to figure something out and submit a PR?
